-- primer esquema
TRUNCATE TABLE esquema_grupo1.listaMensajes,
               esquema_grupo1.registra,
               esquema_grupo1.asociadaAHabitacion,
               esquema_grupo1.Item_Evaluado,
               esquema_grupo1.Reseña_Alojamiento,
               esquema_grupo1.Reseña_Cliente,
               esquema_grupo1.Reseña,
               esquema_grupo1.Pago,
               esquema_grupo1.Estado_Reserva,
               esquema_grupo1.Reserva_Particular,
               esquema_grupo1.Reserva_Hotel,
               esquema_grupo1.Reserva,
               esquema_grupo1.Mensajeria,
               esquema_grupo1.Habitacion,
               esquema_grupo1.Particular,
               esquema_grupo1.Hotel,
               esquema_grupo1.Alojamiento,
               esquema_grupo1.tipohabitacion,
               esquema_grupo1.Usuario_Alojamiento,
               esquema_grupo1.Usuario_cliente
    RESTART IDENTITY CASCADE;

-- segundo esquema
TRUNCATE TABLE esquema_grupo1_alt.listaMensajes,
               esquema_grupo1_alt.registra,
               esquema_grupo1_alt.asociadaAHabitacion,
               esquema_grupo1_alt.Item_Evaluado,
               esquema_grupo1_alt.Reseña_Alojamiento,
               esquema_grupo1_alt.Reseña_Cliente,
               esquema_grupo1_alt.Reseña,
               esquema_grupo1_alt.Pago,
               esquema_grupo1_alt.Estado_Reserva,
               esquema_grupo1_alt.Reserva_Particular,
               esquema_grupo1_alt.Reserva_Hotel,
               esquema_grupo1_alt.Reserva,
               esquema_grupo1_alt.Mensajeria,
               esquema_grupo1_alt.Habitacion,
               esquema_grupo1_alt.Particular,
               esquema_grupo1_alt.Hotel,
               esquema_grupo1_alt.Alojamiento,
               esquema_grupo1_alt.tipohabitacion,
               esquema_grupo1_alt.Usuario_Alojamiento,
               esquema_grupo1_alt.Usuario_cliente
    RESTART IDENTITY CASCADE;
